package com.portais.Ferramentas;

import com.portais.Ferramenta;
import com.portais.SubFerramenta;

public class CódigosArcturianos extends SubFerramenta{
    public CódigosArcturianos (Ferramenta mainFerramenta){
        super(mainFerramenta, "Códicos Arcturianos");

        this.multi = true;
        this.resultados.add("ABERTURA");
        this.resultados.add("ABUNDÂNCIA");
        this.resultados.add("ACEITAÇÃO");
        this.resultados.add("ALEGRIA");
        this.resultados.add("ALTIVEZ");
        this.resultados.add("AMOR INCONDICIONAL");
        this.resultados.add("AMOR PRÓPRIO");
        this.resultados.add("ANCORAGEM");
        this.resultados.add("AQUIESCÊNCIA");
        this.resultados.add("ASCENSÃO");
        this.resultados.add("AUTENTICIDADE");
        this.resultados.add("AUTOCONFIANÇA - SEGURANÇA EM SI MESMO");
        this.resultados.add("AUTOCURA");
        this.resultados.add("AUTO-ESTIMA");
        this.resultados.add("AUTORREFLEXÃO");
        this.resultados.add("AVANÇO - DESCOBERTA");
        this.resultados.add("CAPACITAÇÃO");
        this.resultados.add("CHAMADA");
        this.resultados.add("CHEGADA");
        this.resultados.add("CICLO");
        this.resultados.add("CLAREZA");
        this.resultados.add("CO-CRIAÇÃO");
        this.resultados.add("COMPAIXÃO");
        this.resultados.add("COMUNICAÇÃO");
        this.resultados.add("COMUTAÇÃO");
        this.resultados.add("CONEXÃO");
        this.resultados.add("CONFIRMAÇÃO");
        this.resultados.add("CONHECIMENTO");
        this.resultados.add("CONSCIÊNCIA");
        this.resultados.add("CONSCIÊNCIA CRÍSTICA");
        this.resultados.add("CONSCIÊNCIA DE UNIDADE");
        this.resultados.add("CONSCIÊNCIA INTEGRAL OU DA TOTALIDADE");
        this.resultados.add("CONTATO");
        this.resultados.add("CONVERSÃO - TRANSMUTAÇÃO");
        this.resultados.add("CONVITE");
        this.resultados.add("CRIAÇÃO");
        this.resultados.add("CULPA");
        this.resultados.add("CURA");
        this.resultados.add("DESAPEGO & LIVRAMENTO");
        this.resultados.add("DESDOBRAMENTO");
        this.resultados.add("DESEJO");
        this.resultados.add("DESMASCARAR");
        this.resultados.add("DESPRENDIMENTO");
        this.resultados.add("DEVOÇÃO");
        this.resultados.add("DIREÇÃO");
        this.resultados.add("DUALIDADE");
        this.resultados.add("ECO");
        this.resultados.add("ELEMENTO");
        this.resultados.add("EMERGÊNCIA");
        this.resultados.add("ENTREGA");
        this.resultados.add("EQUILIBRIO");
        this.resultados.add("ESCOLHAS - CAPACIDADE DE ELEGER");
        this.resultados.add("ESSÊNCIA");
        this.resultados.add("EXPANSÃO - DESENVOLVIMENTO");
        this.resultados.add("FÉ - CONFIANÇA");
        this.resultados.add("FLUXO");
        this.resultados.add("FOCO");
        this.resultados.add("FREQUÊNCIA");
        this.resultados.add("GRATIDÃO");
        this.resultados.add("HARMONIA");
        this.resultados.add("ILUMINAÇÃO");
        this.resultados.add("ILUSÃO");
        this.resultados.add("IMPRESSÃO");
        this.resultados.add("INFINITO");
        this.resultados.add("INICIAÇÃO");
        this.resultados.add("INOCÊNCIA");
        this.resultados.add("INTEGRAÇÃO");
        this.resultados.add("INTENÇÃO");
        this.resultados.add("INTUIÇÃO");
        this.resultados.add("LEALDADE");
        this.resultados.add("LIBERAÇÃO");
        this.resultados.add("LIBERDADE");
        this.resultados.add("LIBERTAÇÃO");
        this.resultados.add("LIMITAÇÕES");
        this.resultados.add("MANIFESTAÇÃO");
        this.resultados.add("MESTRE");
        this.resultados.add("MOMENTUM");
        this.resultados.add("MOVIMENTO");
        this.resultados.add("MUDANÇA - MOVIMENTO CONTÍNUO");
        this.resultados.add("MUDANÇA DE TEMPO");
        this.resultados.add("NASCIMENTO");
        this.resultados.add("OPORTUNIDADES");
        this.resultados.add("OPOSTOS");
        this.resultados.add("PACIÊNCIA");
        this.resultados.add("PAIXÃO");
        this.resultados.add("PAZ");
        this.resultados.add("PERDÃO");
        this.resultados.add("PERSEVERANÇA");
        this.resultados.add("PERSPECTIVA");
        this.resultados.add("PLANO DE VIDA");
        this.resultados.add("PLENITUDE");
        this.resultados.add("PODER DE AÇÃO");
        this.resultados.add("PONTO DE INFLEXÃO - MOMENTO CRUCIAL");
        this.resultados.add("PRESENTE - DOM");
        this.resultados.add("PROCESSAMENTO");
        this.resultados.add("PROFUNDO DESPERTAR");
        this.resultados.add("PROJETO");
        this.resultados.add("PROTEÇÃO");
        this.resultados.add("PUREZA");
        this.resultados.add("PURIFICAÇÃO");
        this.resultados.add("REALIZAÇÃO");
        this.resultados.add("RECONHECIMENTO");
        this.resultados.add("RECORDAÇÃO");
        this.resultados.add("REFINAMENTO");
        this.resultados.add("REFORMA");
        this.resultados.add("RENASCIMENTO");
        this.resultados.add("REPETIÇÃO");
        this.resultados.add("RESILIÊNCIA");
        this.resultados.add("RESISTÊNCIA");
        this.resultados.add("RETORNO FINAL");
        this.resultados.add("REVELAÇÃO");
        this.resultados.add("RITMO");
        this.resultados.add("SABEDORIA");
        this.resultados.add("SACRIFÍCIO");
        this.resultados.add("SATISFAÇÃO");
        this.resultados.add("SEM LIMITES");
        this.resultados.add("SEMENTES");
        this.resultados.add("SENSAÇÃO DE SEGURANÇA - BEM-ESTAR");
        this.resultados.add("SENSIBILIDADE");
        this.resultados.add("SEXUALIDADE");
        this.resultados.add("SILÊNCIO");
        this.resultados.add("SINCRONICIDADE");
        this.resultados.add("SINERGIA");
        this.resultados.add("TEMPO NATURAL");
        this.resultados.add("TEMPO DE NASCER DE NOVO");
        this.resultados.add("TERCEIRA ONDA");
        this.resultados.add("TRANSCENDÊNCIA");
        this.resultados.add("TRANSFIGURAÇÃO");
        this.resultados.add("TRANSFORMAÇÃO");
        this.resultados.add("TRANSIÇÃO");
        this.resultados.add("UNIÃO");
        this.resultados.add("UNICIDADE");
        this.resultados.add("VERDADE");
        this.resultados.add("VITÓRIA");
        this.resultados.add("VOZ INTERIOR");
        this.resultados.add("VULNERABILIDADE");

        this.ações.add("'Eu abro meu coração para aspessoas ao meu redor.'");
        this.ações.add("'Eu valorizo o que tenho e estou receptivo para mais.'");
        this.ações.add("'Eu aceito que a mudança precisa ser dividida em etapas.'");
        this.ações.add("'Eu vejo com humor o meu processo.'");
        this.ações.add("'Eu me sinto digno de todas as escolhas que fiz.'");
        this.ações.add("'Eu me amo e estou autorizado a ser.'");
        this.ações.add("'Eu me amo por quem eu sou.'");
        this.ações.add("'Eu aproveito este momento para ancorar o meu crescimento.'");
        this.ações.add("'Este é o tempo de fazer novas escolhas.'");
        this.ações.add("'Eu sou o produtor da minha própria vida.'");
        this.ações.add("'Eu sou um ser especial e único.'");
        this.ações.add("'Eu confio em mim mesmo e nas escolhas que faço.'");
        this.ações.add("Eu posso me curar de tudo.'");
        this.ações.add("'Eu aprecio quem eu sou e o que faço.'");
        this.ações.add("'Eu cresço por ser honesto comigo mesmo sobre o que tenho que mudar.'");
        this.ações.add("'Eu agora escolho pelo meu avanço.'");
        this.ações.add("'Eu tenho a força para realizar o meu sonho.'");
        this.ações.add("'Eu faço as coisas que me dão força agora.'");
        this.ações.add("'Eu tomo o caminho mais curto para o meu destino.'");
        this.ações.add("'Eu estou começando do princípio de um novo ciclo.'");
        this.ações.add("'Eu aponto claramente o que eu quero.'");
        this.ações.add("'Eu e o outro somos um e unidos avançamos.'");
        this.ações.add("'Eu permito aos outros espaço para o processo deles.'");
        this.ações.add("'Eu levo a sério os sinais de meu corpo.'");
        this.ações.add("'Eu sou eu mesmo em todas as situações.'");
        this.ações.add("'Eu me conecto à minha fonte interior de sabedoria.'");
        this.ações.add("'O que eu penso e expresso hoje, será confirmado espontaneamente.'");
        this.ações.add("'Eu confio no conhecimento que está oculto em meu interior.'");
        this.ações.add("'Eu confio que há sempre auxílio quando eu necessito dele.'");
        this.ações.add("'Eu creio nos poderes divinos que eu possuo.'");
        this.ações.add("'Todos nós somos conectados uns aos outros.'");
        this.ações.add("'Eu deixo de lado meu julgamento da situação.'");
        this.ações.add("'Eu faço contato consciente com qual lugar eu quero ir.'");
        this.ações.add("'Eu me apodero de minha liberdade e crio a partir do coração.'");
        this.ações.add("'Eu aceito todos os convites para me desenvolver.'");
        this.ações.add("'Quanto mais estou limpo, mais posso criar tudo que quero.'");
        this.ações.add("'Eu sou responsável apenas pelos meus próprios atos.'");
        this.ações.add("'Eu estou atraindo do espaço o que eu preciso para curar a minha dor.'");
        this.ações.add("'Eu me livro de tudo que restringe meu crescimento.'");
        this.ações.add("'Eu confio as escolhas que faço e aceito os seus frutos.'");
        this.ações.add("'Eu abraço meus desejos e ouso a admiti-los.'");
        this.ações.add("'Eu ouso ser diferente do que é considerado normal.'");
        this.ações.add("'Eu deixo de lado tudo que me sobrecarrega.'");
        this.ações.add("'Eu sou dedicado a mim mesmo.'");
        this.ações.add("'Eu escolho confiante minha própria direção.'");
        this.ações.add("'Eu libero todos os meus julgamentos.'");
        this.ações.add("'Eu percebo com clareza tanto o que transmito quanto o que recebo,através dos ecos da Alma.'");
        this.ações.add("'Eu nasci para o que faço.'");
        this.ações.add("'Eu assumo o desafio de mostrar quem eu realmente sou.'");
        this.ações.add("'Eu abro meu coração, entregando-me inteiramente a ele.'");
        this.ações.add("'Eu estou firme e equilibrado.'");
        this.ações.add("'Eu aceito as consequências das escolhas que fiz.'");
        this.ações.add("'Confio na sabedoria de minha alma.'");
        this.ações.add("'Eu tenho tudo em mim para ser bem sucedido.'");
        this.ações.add("'Eu tenho fé no que sinto se aproximar.'");
        this.ações.add("'Eu entro nas ondas de minha criação.'");
        this.ações.add("'Eu estou focado no que me faz feliz.'");
        this.ações.add("'Eu estou emitindo minha própria frequência.'");
        this.ações.add("'Eu sou grato por tudo que me fez ser quem eu sou.'");
        this.ações.add("'Eu vivo em harmonia com meu Eu Interior e o meu ambiente.'");
        this.ações.add("'Tudo o que eu experimento me ajuda a ficar mais iluminado.'");
        this.ações.add("'Eu estou acima do meu medo da mudança.'");
        this.ações.add("'Eu prezo pelo que tenho alcançado até agora.'");
        this.ações.add("'Meu poder é grande e infinito.'");
        this.ações.add("'Eu vivo em liberdade.'");
        this.ações.add("'Eu estou autorizado a brincar livre como uma criança.'");
        this.ações.add("'Eu faço parte das lições da minha vida diariamente.'");
        this.ações.add("'Eu levo minhas intenções a sério.'");
        this.ações.add("'Eu escuto meus sentimentos e ajo em direção a eles.'");
        this.ações.add("'Eu sou leal a mim mesmo e ao que eu defendo.'");
        this.ações.add("'Eu dou liberdade para a minha criança interior.'");
        this.ações.add("'Eu me dou a liberdade de Ser.'");
        this.ações.add("'Eu me liberto das críticas que faço sobre mim mesmo.'");
        this.ações.add("'Eu continuo o que eu comecei.'");
        this.ações.add("'Eu ouso manifestar o que eu realmente quero.'");
        this.ações.add("'Eu sou o que eu sou, livre para ser.'");
        this.ações.add("'Eu confio que, no momento certo, farei o que tenho que fazer.'");
        this.ações.add("'Eu percorro meu caminho no meu próprio ritmo.'");
        this.ações.add("'Eu me conecto com a energia do momento.'");
        this.ações.add("'Eu tenho tempo suficiente para fazer tudo que eu quero.'");
        this.ações.add("'Hoje eu saúdo meu novo Eu.'");
        this.ações.add("'Eu tenho infinitas possibilidades para alcançar o sucesso.'");
        this.ações.add("'Eu renuncio a julgar.'");
        this.ações.add("'Eu estou deixando passar minhas expectativas e abrindo-me para aquil o que é possível receber.'");
        this.ações.add("'Se eu faço o que eu gosto de fazer, tudo dará certo.'");
        this.ações.add("'Eu crio a paz em mim e na minha vida.'");
        this.ações.add("'Eu me perdoo pelo que eu tenha gostado de fazer de forma diferente.'");
        this.ações.add("'Eu sei o que eu quero e para onde vou.'");
        this.ações.add("'Eu posso transformar qualquer situação a meu favor.'");
        this.ações.add("'Eu creio que minha alma tem acompanhado o plano de vida.'");
        this.ações.add("'Eu reconheço todas as minhas características, boas ou más.'");
        this.ações.add("'Eu converto meus planos em ações.'");
        this.ações.add("'É hora de fazê-lo de forma diferente.'");
        this.ações.add("'Eu reconheço meu dom sem igual.'");
        this.ações.add("'Eu assimilo meu passado em paz e quietude.'");
        this.ações.add("'Eu estou ciente do que me ajuda a avançar e do que me obstrui.'");
        this.ações.add("'Eu confio no plano que me trouxe até aqui.'");
        this.ações.add("'Eu estou emitindo minhas próprias frequências.'");
        this.ações.add("'Eu respondo aos outros com pureza.'");
        this.ações.add("'Eu me curo, tornando-me honesto comigo mesmo.'");
        this.ações.add("'Eu percebo que posso criar o que eu quero.'");
        this.ações.add("'Eu me concedo a oportunidade de cometer erros.'");
        this.ações.add("'Eu me lembro para o que eu nasci.'");
        this.ações.add("'Eu estou autorizado a desfrutar o meu processo de crescimento.'");
        this.ações.add("'Eu estou pronto para realizar a reforma interior que me libertará.'");
        this.ações.add("'Eu me desprendo de tudo o que é velho e me envolvo com o que é novo.'");
        this.ações.add("'Cada repetição é um novo desafio para crescer.'");
        this.ações.add("'Eu também supero os deslizes e recaídas.'");
        this.ações.add("'Eu faço o que eu realmente quero.'");
        this.ações.add("'Eu sou o mestre do meu próprio processo criativo.'");
        this.ações.add("'É hora de mostrar quem eu realmente sou.'");
        this.ações.add("'Eu faço escolhas que ressoam com o ritmo da vida.'");
        this.ações.add("'A resposta para quem eu sou encontra-se dentro de mim.'");
        this.ações.add("'Eu escolho conscientemente alcançar meu objetivo.'");
        this.ações.add("'Eu aumento a qualidade da minha vida.'");
        this.ações.add("'Meu poder é ilimitado.'");
        this.ações.add("'Hoje eu planto as sementes de meus ideais.'");
        this.ações.add("'Eu preciso somente de mim para me sentir seguro.'");
        this.ações.add("'Eu confio em minhas sensações e nos sinais que eu capto.'");
        this.ações.add("'Eu posso me dar amor.'");
        this.ações.add("'Eu me conecto com o silêncio em meu coração.'");
        this.ações.add("'Eu estou alerta aos símbolos que indicam o caminho.'");
        this.ações.add("'Minha cabeça e coração são um.'");
        this.ações.add("'Eu entro em sintonia com o ritmo da natureza.'");
        this.ações.add("'Eu me ofereço a uma nova chance.'");
        this.ações.add("'Eu me responsabilizo por um mundo melhor.'");
        this.ações.add("'Eu transcendo meus medos e limitações.'");
        this.ações.add("'Eu aceito o desafio de mudar.'");
        this.ações.add("'Eu vou ao limite para realizar meu sonho.'");
        this.ações.add("'Eu me entrego ao desconhecido.'");
        this.ações.add("'Eu compartilho meu coração, porque eu sou um desbravador.'");
        this.ações.add("'O que eu penso e sinto são igualmente importantes.'");
        this.ações.add("'Minha verdade é fundamentada no que eu sinto.'");
        this.ações.add("'Eu vou fazê-lo!'");
        this.ações.add("'Eu estou sempre ouvindo a sabedoria de meu coração.'");
        this.ações.add("'Eu ouso mostrar minha vulnerabilidade.'");
        
        

        this.repeatString = "(nº e designação),  ";
        this.repeatString2 = "(simbolo), ";
        this.ownDecreto = "Na divina presença do Eu Sou de (nome do terapeuta) abro a frequência do método de Cura Quântica Multidimensional pedindo ao Eu Superior de (nome do consulente) permissão para atuar no seu campo morfogenético com as frequências de Cura dos Códigos Arcturianos. Acedendo ao campo cósmico de comunicação estelar e ativando os aparelhos etéreos de aplicação dos códigos. Ativo agora o código (next) na frequência certa e na quantidade exata e ordeno que se fixe no campo morfogenético de (nome do consulente) operando a cura e a transformação interior em todos os corpos e todos os chakras. (next2) Encerro agora a comunicação com o campo cósmico de comunicação estelar e todos os aparelhos etéreos de aplicação. Fechando o campo morfogenético e a Merkabah Pessoal de (nome do consulente) e ordeno que se fixem todas as frequências de cura, agora.";
        
    }
}
