package com.portais.Ferramentas;

import com.portais.Ferramenta;
import com.portais.Portal;

public class GeometriasFrequenciais extends Ferramenta{
    public GeometriasFrequenciais (Portal portal, int id){
        super("Geometrias Frequenciais", portal, id);
        
        this.multi = true;
        this.resultados.add("Círculo");
        this.resultados.add("Vesica Piscis");
        this.resultados.add("Triângulo Equilátero");
        this.resultados.add("Semente da Vida");
        this.resultados.add("Toróide");
        this.resultados.add("Ovo da Vida");
        this.resultados.add("Árvore da Vida");
        this.resultados.add("Flor da Vida");
        this.resultados.add("Cubo de Metatron");
        this.resultados.add("Tetraedro");
        this.resultados.add("Cubo");
        this.resultados.add("Octaedro");
        this.resultados.add("Icosaedro");
        this.resultados.add("Dodecaedro");
        this.resultados.add("Merkabah");
        this.resultados.add("Phi");
        this.resultados.add("Malkuth");
        this.resultados.add("Yesod");
        this.resultados.add("Nitzach");
        this.resultados.add("Tipheret");
        this.resultados.add("Hod");
        this.resultados.add("Pechod");
        this.resultados.add("Chesed");
        this.resultados.add("Binah");
        this.resultados.add("Chokmah");
        this.resultados.add("Kether");
        this.resultados.add("Tesseract");
        this.resultados.add("Elipse");
        this.resultados.add("Vórtice");
        this.resultados.add("Espiral");
        this.resultados.add("Nó Górdio");
        this.resultados.add("Flor de Lótus");
        this.resultados.add("Alowa");
        this.resultados.add("Amor Alquímico");
        this.resultados.add("Avalion");
        this.resultados.add("Bareth");
        this.resultados.add("Buda Shat");
        this.resultados.add("Comando Twitan");
        this.resultados.add("Cho Ku Rei");
        this.resultados.add("Cristal");
        this.resultados.add("Dai Ko Mio");
        this.resultados.add("Dai Ko Wa Sho");
        this.resultados.add("Dai Ran Yan");
        this.resultados.add("Dax Hum");
        this.resultados.add("Emenonfa");
        this.resultados.add("Emu");
        this.resultados.add("Eveg");
        this.resultados.add("Gnosa");
        this.resultados.add("Halu");
        this.resultados.add("Haman");
        this.resultados.add("Hanik");
        this.resultados.add("Hexin");
        this.resultados.add("Hart");
        this.resultados.add("Hon Sha Zen Shonen");
        this.resultados.add("Sei He Ki");
        this.resultados.add("Iava");
        this.resultados.add("Infinex");
        this.resultados.add("In Sha Sol");
        this.resultados.add("Ka Me Akque");
        this.resultados.add("Killet");
        this.resultados.add("Krash Hum");
        this.resultados.add("Krya");
        this.resultados.add("Look Sham Too");
        this.resultados.add("Mixanan");
        this.resultados.add("Om Metistica");
        this.resultados.add("Acaresh");
        this.resultados.add("Shaalam");
        this.resultados.add("Melvic");
        this.resultados.add("Santa Ametista");
        this.resultados.add("Santa Esmeralda");
        this.resultados.add("Shamlin");
        this.resultados.add("Comando thisoral");
        this.resultados.add("Om Plash");
        this.resultados.add("Yesh");
        this.resultados.add("Om Miguel");
        this.resultados.add("Tan Trim");
        this.resultados.add("Tesmate");
        this.resultados.add("Om Cristo");
        this.resultados.add("Om Maria");
        this.resultados.add("Yom Too");
        this.resultados.add("Malatiel");
        this.resultados.add("Menaton");
        this.resultados.add("Menshui");
        this.resultados.add("Meltrix");
        this.resultados.add("Surilh");
        this.resultados.add("Ramethom");
        this.resultados.add("Om Thalom");
        this.resultados.add("Lian So");
        this.resultados.add("Talmar");
        this.resultados.add("Vantil");
        this.resultados.add("Caloth");
        this.resultados.add("Tantar");
        this.resultados.add("Om Micah");
        this.resultados.add("Zech");
        this.resultados.add("Acaresh");
        this.resultados.add("Om Shanti Om");
        this.resultados.add("Decágono");
        this.resultados.add("Hiranya");
        this.resultados.add("Alta Vitalidade");
        this.resultados.add("Omega-Alfa");
        this.resultados.add("Keiti");
        this.resultados.add("SCAP");
        this.resultados.add("Tri-Círculo");
        this.resultados.add("Mesa D’Amiens");
        this.resultados.add("Turbilhão");
        this.resultados.add("Peggotty Board");
        this.resultados.add("Telerradiador");
        this.resultados.add("Compensador Mindtron");
        this.resultados.add("Cruz Atlante");
        this.resultados.add("Labirinto D’Amiens");
        this.resultados.add("Pirâmide Plana");
        this.resultados.add("Kit-Cromo");
        this.resultados.add("Baguá");
        this.resultados.add("Srim-Hrim-Krim-Klim");
        this.resultados.add("IAVE");
        this.resultados.add("Anti Magia");
        this.resultados.add("Nove Círculos");
        this.resultados.add("Escudo");
        this.resultados.add("Anti-Dor");
        this.resultados.add("Desimpregnador");
        this.resultados.add("Cruz Ansata");
        this.resultados.add("Ventoinha");
        this.resultados.add("Transmutador");
        this.resultados.add("Diafragma");
        
        this.repeatString = "(resultado), ";
        this.Decreto = "Na divina presença do Eu Sou de (nome do terapeuta) abro a frequência do método de Cura Quântica Multidimensional e a Ressonância Harmonica das Geometrias Sagradas pedindo ao Eu Superior de (nome do consulente) permissão para atuar e imprimir a frequência de cura no seu campo morfogenético impactando todos os chakras e todos os corpos sutis. Ativo agora a frequência de/do/da (next) para que pulse(m) na harmonia e alinhamento de consciência de (nome do consulente) na quantidade certa e na medida exata. Pulsa no campo, pulsa no campo, pulsa no campo.";

        
    }
}
