package com.portais.Ferramentas;

import com.portais.Ferramenta;
import com.portais.Portal;
import com.portais.SubFerramenta;

public class MatrizBioenergéticaEMeridional extends Ferramenta{
    public MatrizBioenergéticaEMeridional (Portal portal, int id){
        super("Matriz Bioenergética e Meridional", portal, id);

        SubFerramenta intermedFerramenta;
        SubFerramenta intermedSubFerramenta;

        this.type = 2;
        
        this.resultados.add("Matriz Bioenergética");
        this.resultados.add("Meridianos do Corpo");
        this.resultados.add("Pontos Acupuntura");
        this.resultados.add("Tabela Periódica dos Elementos");

        intermedFerramenta = new SubFerramenta(this, "Matriz Bioenergética");
        intermedFerramenta.multi = true;
        intermedFerramenta.resultados.add("Da rede cósmica de entrelaçamento");
        intermedFerramenta.resultados.add("Da informação holográfica");
        intermedFerramenta.resultados.add("Do direcionamento da informação");
        intermedFerramenta.resultados.add("Da reconstrução embrionária do campo");
        intermedFerramenta.resultados.add("Da influência dos corpos sutis");
        intermedFerramenta.resultados.add("Das formas pensamento como influenciadoras energéticas");
        intermedFerramenta.resultados.add("Da somatização emocional e mental no corpo físico");
        intermedFerramenta.resultados.add("Da projeção do campo na saúde");
        intermedFerramenta.resultados.add("Da memória da água na cura");
        intermedFerramenta.resultados.add("Da homeostase do corpo físico através do campo");
        
        intermedFerramenta.ações.add("Unir as consciências");
        intermedFerramenta.ações.add("Reconstrução Física");
        intermedFerramenta.ações.add("Foco na Cura");
        intermedFerramenta.ações.add("Retornar o DNA ao propósito");
        intermedFerramenta.ações.add("Reestruturação dos corpos sutis");
        intermedFerramenta.ações.add("Ativar pensamentos de cura");
        intermedFerramenta.ações.add("Limpar todos os registros energéticos negativos dos corpos sutis");
        intermedFerramenta.ações.add("Regenerar o campo bioenergético");
        intermedFerramenta.ações.add("Programar a matriz química da água no corpo e no ambiente para a cura");
        intermedFerramenta.ações.add("Auto-regeneração do corpo físico");

        intermedFerramenta.repeatString = "Princípio (princípio) para (ação), ";
        intermedFerramenta.ownDecreto = "Na divina presença do Eu Sou de (nome do terapeuta) abro a frequência do método de Cura Quântica Multidimensional e a Matriz da Bioenergética Sutil pedindo ao Eu Superior de (nome do consulente) permissão para atuar nos seus campos, chakras e corpos sutis. Ativo agora a frequência do (next). Que pulsem na harmonia e alinhamento de consciência de (nome do consulente) na quantidade certa e na medida exata. Pulsa no campo, pulsa no campo, pulsa no campo.";
        this.subFerramentas.add(intermedFerramenta);

        intermedFerramenta = new MeridianosDoCorpo(this);
        this.subFerramentas.add(intermedFerramenta);

        intermedFerramenta = new PontosAcupuntura(this);
        this.subFerramentas.add(intermedFerramenta);

        intermedFerramenta = new SubFerramenta(this, "Tabela Periódica dos Elementos");
        intermedFerramenta.ownDecreto = "Na divina presença do Eu Sou de (nome do terapeuta) abro a frequência do método de Cura Quântica Multidimensional e a Matriz da Tabela Periódica com a função de equilibrar as funções do elemento nos campos atuantes e pedindo ao Eu Superior de (nome do consulente) permissão para atuar nos seus campos, chakras e corpos sutis. Ativo agora a frequência do elemento (nome do elemento) para que se fixe na harmonização do propósito do consulente. Que pulsem na harmonia e alinhamento de consciência de (nome do consulente) na quantidade certa e na medida exata. Pulsa no campo, pulsa no campo, pulsa no campo.";
        
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");
        intermedFerramenta.resultados.add("");

        //1
        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Hidrogénio");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("Hélio");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        //2
        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Lítio");
        intermedSubFerramenta.resultados.add("Berílio");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("Boro");
        intermedSubFerramenta.resultados.add("Carbono");
        intermedSubFerramenta.resultados.add("Nitrogénio");
        intermedSubFerramenta.resultados.add("Oxigénio");
        intermedSubFerramenta.resultados.add("Flúor");
        intermedSubFerramenta.resultados.add("Neon");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Sódio");
        intermedSubFerramenta.resultados.add("Magnésio");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("Alumínio");
        intermedSubFerramenta.resultados.add("Silício");
        intermedSubFerramenta.resultados.add("Fósforo");
        intermedSubFerramenta.resultados.add("Enxofre");
        intermedSubFerramenta.resultados.add("Cloro");
        intermedSubFerramenta.resultados.add("Árgon");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Potássio");
        intermedSubFerramenta.resultados.add("Cálcio");
        intermedSubFerramenta.resultados.add("Escândio");
        intermedSubFerramenta.resultados.add("Titânio");
        intermedSubFerramenta.resultados.add("Vanádio");
        intermedSubFerramenta.resultados.add("Cromo");
        intermedSubFerramenta.resultados.add("Manganês");
        intermedSubFerramenta.resultados.add("Ferro");
        intermedSubFerramenta.resultados.add("Cobalto");
        intermedSubFerramenta.resultados.add("Níquel");
        intermedSubFerramenta.resultados.add("Cobre");
        intermedSubFerramenta.resultados.add("Zinco");
        intermedSubFerramenta.resultados.add("Gálio");
        intermedSubFerramenta.resultados.add("Germânio");
        intermedSubFerramenta.resultados.add("Arsénio");
        intermedSubFerramenta.resultados.add("Selénio");
        intermedSubFerramenta.resultados.add("Bromo");
        intermedSubFerramenta.resultados.add("Cripton");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Rubídio");
        intermedSubFerramenta.resultados.add("Estrôncio");
        intermedSubFerramenta.resultados.add("Ítrio");
        intermedSubFerramenta.resultados.add("Zircônio");
        intermedSubFerramenta.resultados.add("Nióbio");
        intermedSubFerramenta.resultados.add("Molibdénio");
        intermedSubFerramenta.resultados.add("Tenécio");
        intermedSubFerramenta.resultados.add("Ruténio");
        intermedSubFerramenta.resultados.add("Ródio");
        intermedSubFerramenta.resultados.add("Paládio");
        intermedSubFerramenta.resultados.add("Prata");
        intermedSubFerramenta.resultados.add("Cádmio");
        intermedSubFerramenta.resultados.add("Índio");
        intermedSubFerramenta.resultados.add("Estanho");
        intermedSubFerramenta.resultados.add("Antimónio");
        intermedSubFerramenta.resultados.add("Telúrio");
        intermedSubFerramenta.resultados.add("Iodo");
        intermedSubFerramenta.resultados.add("Xénon");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Césio");
        intermedSubFerramenta.resultados.add("Bário");
        intermedSubFerramenta.resultados.add("");
        intermedSubFerramenta.resultados.add("Háfnio");
        intermedSubFerramenta.resultados.add("Tântalo");
        intermedSubFerramenta.resultados.add("Tungsténio");
        intermedSubFerramenta.resultados.add("Rénio");
        intermedSubFerramenta.resultados.add("Ósmio");
        intermedSubFerramenta.resultados.add("Irídio");
        intermedSubFerramenta.resultados.add("Platina");
        intermedSubFerramenta.resultados.add("Ouro");
        intermedSubFerramenta.resultados.add("Mercúrio");
        intermedSubFerramenta.resultados.add("Tálio");
        intermedSubFerramenta.resultados.add("Chumbo");
        intermedSubFerramenta.resultados.add("Bismuto");
        intermedSubFerramenta.resultados.add("Polónio");
        intermedSubFerramenta.resultados.add("Ástato");
        intermedSubFerramenta.resultados.add("Rádon");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("Frâncio");
        intermedSubFerramenta.resultados.add("Rádio");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("Rutherfórdio");
        intermedSubFerramenta.resultados.add("Dúbnio");
        intermedSubFerramenta.resultados.add("Seabórgio");
        intermedSubFerramenta.resultados.add("Bóhrio");
        intermedSubFerramenta.resultados.add("Hássio");
        intermedSubFerramenta.resultados.add("Meitnério");
        intermedSubFerramenta.resultados.add("Darmstácio");
        intermedSubFerramenta.resultados.add("Roentgénio");
        intermedSubFerramenta.resultados.add("Copernício");
        intermedSubFerramenta.resultados.add("Nipónio");
        intermedSubFerramenta.resultados.add("Fleróvio");
        intermedSubFerramenta.resultados.add("Moscóvio");
        intermedSubFerramenta.resultados.add("Livermório");
        intermedSubFerramenta.resultados.add("Tenesso");
        intermedSubFerramenta.resultados.add("Oganésson");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("Lantânio");
        intermedSubFerramenta.resultados.add("Cério");
        intermedSubFerramenta.resultados.add("Praseodímio");
        intermedSubFerramenta.resultados.add("Neodímio");
        intermedSubFerramenta.resultados.add("Promécio");
        intermedSubFerramenta.resultados.add("Samário");
        intermedSubFerramenta.resultados.add("Európio");
        intermedSubFerramenta.resultados.add("Gadolínio");
        intermedSubFerramenta.resultados.add("Térbio");
        intermedSubFerramenta.resultados.add("Disprósio");
        intermedSubFerramenta.resultados.add("Hólmio");
        intermedSubFerramenta.resultados.add("Érbio");
        intermedSubFerramenta.resultados.add("Túlio");
        intermedSubFerramenta.resultados.add("Itérbio");
        intermedSubFerramenta.resultados.add("Lutécio");
        
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);

        intermedSubFerramenta = new SubFerramenta(this, "");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("[Elemento Não Existente]");
        intermedSubFerramenta.resultados.add("Actínio");
        intermedSubFerramenta.resultados.add("Tório");
        intermedSubFerramenta.resultados.add("Protactínio");
        intermedSubFerramenta.resultados.add("Urânio");
        intermedSubFerramenta.resultados.add("Neptúnio");
        intermedSubFerramenta.resultados.add("Plutónio");
        intermedSubFerramenta.resultados.add("Amerício");
        intermedSubFerramenta.resultados.add("Cúrio");
        intermedSubFerramenta.resultados.add("Berkélio");
        intermedSubFerramenta.resultados.add("Califórnio");
        intermedSubFerramenta.resultados.add("Einsténio");
        intermedSubFerramenta.resultados.add("Férmio");
        intermedSubFerramenta.resultados.add("Mendelévio");
        intermedSubFerramenta.resultados.add("Nobélio");
        intermedSubFerramenta.resultados.add("Lawrêncio");
        
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ações.add("");
        intermedSubFerramenta.ownDecreto = intermedFerramenta.ownDecreto;
        intermedFerramenta.subFerramentas.add(intermedSubFerramenta);


        this.subFerramentas.add(intermedFerramenta);

    }
}
