package com.portais.Ferramentas;

import com.portais.Ferramenta;
import com.portais.SubFerramenta;

public class NomesDeDeus72 extends SubFerramenta{
    public NomesDeDeus72 (Ferramenta mainFerramenta){
        super(mainFerramenta, "72 Nomes de Deus");

        this.resultados.add("KAF HE KAF");
        this.resultados.add("YOD LAMED YOD");
        this.resultados.add("YEY YOD SAMEKH");
        this.resultados.add("MEM LAMED AYIN");
        this.resultados.add("SHIN HE MEM");
        this.resultados.add("HE LAMED LAMED");
        this.resultados.add("ALEF KAF ALEF");
        this.resultados.add("HE TAV KAF");
        this.resultados.add("HE ZAYIN YOD");
        this.resultados.add("DALET LAMED ALEF");
        this.resultados.add("KAF ALEF LAMED");
        this.resultados.add("AYIN HE HE");
        this.resultados.add("LAMED ZAYIN YOD");
        this.resultados.add("HE BET MEM");
        this.resultados.add("YOD RESH HE");
        this.resultados.add("MEM QOPH HE");
        this.resultados.add("KAF ALEF LAMED");
        this.resultados.add("YOD LAMED KAF");
        this.resultados.add("KAF KAF LAMED");
        this.resultados.add("LAMED HE PE");
        this.resultados.add("KAF LAMED NUN");
        this.resultados.add("YOD YOD YOD");
        this.resultados.add("MEM LAMED HE");
        this.resultados.add("KAF HE HET");
        this.resultados.add("HE TAV NUN");
        this.resultados.add("ALEF ALEF HE");
        this.resultados.add("TAV RESH YOD");
        this.resultados.add("HE ALEF SHIN");
        this.resultados.add("YOD YOD RESH");
        this.resultados.add("MEM KAF ALEF");
        this.resultados.add("BET KAF LAMED");
        this.resultados.add("KAF SHIN RESH");
        this.resultados.add("KAF HET YOD");
        this.resultados.add("HET HE LAMED");
        this.resultados.add("QOPH KAF KAF");
        this.resultados.add("DALET NUN MEM");
        this.resultados.add("YOD NUN ALEF");
        this.resultados.add("MEM AYIN HET");
        this.resultados.add("AYIN HE RESH");
        this.resultados.add("ZAYIN YOD YOD");
        this.resultados.add("HE HE HE");
        this.resultados.add("KAF YOD MEM");
        this.resultados.add("LAMED KAF KAF");
        this.resultados.add("HE LAMED YOD");
        this.resultados.add("LAMED ALEF SAMEKH");
        this.resultados.add("YOD RESH AYIN");
        this.resultados.add("LAMED SHIN AYIN");
        this.resultados.add("HE YOD MEM");
        this.resultados.add("KAF HE KAF");
        this.resultados.add("YOD NUN DALET");
        this.resultados.add("SHIN HET HE");
        this.resultados.add("MEM MEM AYIN");
        this.resultados.add("ALEF NUN NUN");
        this.resultados.add("NUN YOD TAV");
        this.resultados.add("HE BET MEM");
        this.resultados.add("YOD KAF PE");
        this.resultados.add("MEM MEM NUN");
        this.resultados.add("LAMED YOD YOD");
        this.resultados.add("HET RESH HE");
        this.resultados.add("RESH TZADIK MEM");
        this.resultados.add("BET MEM KAF");
        this.resultados.add("HE HE YOD");
        this.resultados.add("KAF NUN AYIN");
        this.resultados.add("YOD HET MEM");
        this.resultados.add("BET MEM DALET");
        this.resultados.add("QOPH NUN MEM");
        this.resultados.add("AYIN YOD ALEF");
        this.resultados.add("KAF BET HET");
        this.resultados.add("HE ALEF RESH");
        this.resultados.add("MEM BET YOD");
        this.resultados.add("YOD YOD HE");
        this.resultados.add("MEM VAM MEM");

        this.resultados2.add("Viagem no Tempo: Como consertar o passado");
        this.resultados2.add("Resgatando as Centelhas: Recarregando quando está esgotado");
        this.resultados2.add("Fazendo Milagres: Uma receita");
        this.resultados2.add("Eliminando Pensamentos Negativos: Quando e como");
        this.resultados2.add("Cura: Meditação para si próprio e para os outros");
        this.resultados2.add("Estado de Sonho: Ativando mensagens do subconsciente");
        this.resultados2.add("DNA da Alma: Recolocando as coisas no seu estado perfeito");
        this.resultados2.add("Neutralizando Energia Negativa e Estresse: Aliviando a pressão");
        this.resultados2.add("Influências Angelicais: Acessando a ajuda divina");
        this.resultados2.add("Olhares Podem Matar: Protegendo-se do mau-olhado");
        this.resultados2.add("Expulsando os Resíduos do Mal: Purificando os lugares");
        this.resultados2.add("Amor Incondicional: Como despertar o amor, principalmente quando você não quer fazê-lo");
        this.resultados2.add("Paraíso na Terra: Criando harmonia dentro e fora.");
        this.resultados2.add("Adeus às Armas: Parando o conflito");
        this.resultados2.add("Visão de Longo Alcance: Vendo o efeito de decisões antes de tomá-las");
        this.resultados2.add("Jogando Fora a Depressão: Como se levantar depois da queda.");
        this.resultados2.add("Grande Fuga: Vencendo os limites do ego.");
        this.resultados2.add("Fertilidade: Quando é difícil engravidar.");
        this.resultados2.add("Disque Deus: Recebendo respostas para suas orações.");
        this.resultados2.add("Vencendo os Vícios: Sobrepujando seu lado negativo.");
        this.resultados2.add("Erradicando a Praga: Efetuando mudanças no mundo físico.");
        this.resultados2.add("Banindo a Atração Fatal: Como parar de atrair as pessoas erradas para sua vida.");
        this.resultados2.add("Compartilhando a Chama: Passando adiante a sabedoria.");
        this.resultados2.add("Ciúme: Desfazendo o caos resultante de seu ciúme antes que ele se manifeste.");
        this.resultados2.add("Fale o que Está Pensando: Para aqueles momentos em que você precisa de ajuda para expressar a verdade");
        this.resultados2.add("Ordem a Partir do Caos: Revertendo a Lei de Murphy.");
        this.resultados2.add("Sócia Silenciosa: Escolhendo a luz como sua sócia");
        this.resultados2.add("Alma Gêmea: Atraindo a pessoa certa.");
        this.resultados2.add("Eliminando o Ódio: Expurgando o veneno");
        this.resultados2.add("Construindo Pontes: Consertando relacionamentos destruídos.");
        this.resultados2.add("Termine o que Começou: Encontrando forças para terminar o que começou.");
        this.resultados2.add("Memórias: Quebrando o ciclo");
        this.resultados2.add("Revelando o Lado Negro: Eliminando os obstáculos que você cria");
        this.resultados2.add("Esqueça Você Mesmo: Abrindo-se para uma outra visão");
        this.resultados2.add("Energia Sexual: Como receber mais de sua experiência sexual");
        this.resultados2.add("(Sem) Medo: Desatando os nós");
        this.resultados2.add("Plano Geral: Vendo o bem oculto em cada desafio");
        this.resultados2.add("Circuito: Compartilhando para poder receber");
        this.resultados2.add("Diamante em Estado Bruto: Transformando o carvão da sua vida em diamantes.");
        this.resultados2.add("Falando as Palavras Certas: Usando a língua para fazer coisas boas acontecerem.");
        this.resultados2.add("Auto-estima: Encontrando forças para se erguer");
        this.resultados2.add("Revelando o Oculto: Vendo a verdade e lidando com ela");
        this.resultados2.add("Desafiando a Gravidade: Realizando o poder da mente sobre a matéria.");
        this.resultados2.add("Amenizando o Julgamento: Desviando-se do bumerangue que você lançou parar o julgamento contra você.");
        this.resultados2.add("O Poder da Prosperidade: O que fazer quando você precisa de dinheiro");
        this.resultados2.add("Certeza Absoluta: O que fazer quando a dúvida surge.");
        this.resultados2.add("Transformação Global: Ajudando a trazer a paz mundial");
        this.resultados2.add("Unidade: Quando há conflito e a única solução é a união");
        this.resultados2.add("Felicidade: Quando você precisa de força para escoher a felicidade.");
        this.resultados2.add("O Suficiente Nunca É Suficiente: Quando você precisa da paixão para não se contentar com menos.");
        this.resultados2.add("Sem Culpa: Eliminando aspectos negativos de sua natureza e reprimindo os danos que eles causaram.");
        this.resultados2.add("Paixão: Despertando o anseio em seu coração");
        this.resultados2.add("Sem Interesse Próprio: Dando sem esperar nada em troca");
        this.resultados2.add("A Morte da Morte: Quando tudo vai bem e você quer que continue assim.");
        this.resultados2.add("Pensamento em Ação: Força para fazer acontecer.");
        this.resultados2.add("Dissipando a Raiva: Derrotando-a antes que ela derrote você.");
        this.resultados2.add("Escutando Sua Alma: Aumentando o volume da suave voz interior");
        this.resultados2.add("Seguindo em Frente: Quando você precisa de força para seguir seu caminho");
        this.resultados2.add("Cordão Umbilical: Conectando-se com a força vital");
        this.resultados2.add("Liberdade: Passando no teste e indo para o próximo nível");
        this.resultados2.add("Água: Removendo negatividade da fonte da vida.");
        this.resultados2.add("Pais - Mestres, Não Pregadores: Quando você precisa ensinar seus filhos.");
        this.resultados2.add("Valorização: Como manter o que você tem e receber mais.");
        this.resultados2.add("Projetando uma Imagem Positiva de Si Mesmo: Revelando o melhor em você");
        this.resultados2.add("Temor a Deus: Quando você precisa se lembrar de que existe um sistema, e de como operá-lo.");
        this.resultados2.add("Responsabilidade: O poder para assumir responsabilidade por sua felicidade e sua vida");
        this.resultados2.add("Grandes Expectativas: Como não se decepcionar mais");
        this.resultados2.add("Contatando Almas que Partiram: Fazendo conexões positivas com pessoas que faleceram.");
        this.resultados2.add("Achados e Perdidos: O que fazer quando você está perdido e confuso");
        this.resultados2.add("Reconhecendo um Projeto por Trás da Desordem: Encontrando a solução no problema.");
        this.resultados2.add("Profecia e Universos Paralelos: Trocando seu universo por um melhor.");
        this.resultados2.add("Purificação Espiritual: Purificando-se de negatividade.");
        
        this.ações.add("Retificar o Passado desde a Semente da Criação e Atrair a felicidade");
        this.ações.add("Resgate da Centelha Divina Recuperar a energia e oportunidades roubadas");
        this.ações.add("Acessar Milagres");
        this.ações.add("Saia do Mundo das Ilusões e Limpe Pensamentos Destrutivo");
        this.ações.add("Curar o Corpo, a Mente e a Alma");
        this.ações.add("Louvor e Viagem Astral");
        this.ações.add("Retifique o DNA de sua Alma");
        this.ações.add("Limpe toda negatividade interna e externa");
        this.ações.add("Atraia Anjos de Luz e a Boa Sorte");
        this.ações.add("Regeneração de Órgãos Doentes ou Danificados e Proteção contra Inveja e Pesadelos");
        this.ações.add("Retirar o Peso da Vida e Retificar o Ego");
        this.ações.add("Ativar o Amor Incondicional e Trazer Alegria");
        this.ações.add("Desperte a Luz do Messias Interior");
        this.ações.add("Paz Interna e Externa");
        this.ações.add("Aconselhe-se com seu Eu Superior intuindo o que vai acontecer");
        this.ações.add("Livre-se da depressão e Anime-se completamente");
        this.ações.add("Retirar o Peso da Vida e Retificar o Ego");
        this.ações.add("Acesse o Recipiente Coletivo e Solucione Problemas com Fertilidade");
        this.ações.add("Falar com Deus Elevar almas a mundos de Luz");
        this.ações.add("Libertar-se dos vícios. Fortalecer a Consciência Espiritual");
        this.ações.add("Superar limites e Fechar-se para ações reativas");
        this.ações.add("Cura mental e psicológica e Para afastar pessoas negativas");
        this.ações.add("Ativar a Luz e o Verbo Divinos e Para atrair alegria");
        this.ações.add("Libertar-se do ciúme, inveja, dor, sofrimento e vícios");
        this.ações.add("Falar e Ouvir a Verdade");
        this.ações.add("Eliminar o Caos de sua vida e Para melhorar a Organização do Tempo");
        this.ações.add("Pacto de Prosperidade com Deus mediante pagamento de dízimo (doações para obras de caridade, preservação da natureza ou de expansão da Luz)");
        this.ações.add("Atrair a Alma Gémea");
        this.ações.add("Para retirar o Ódio e Para Aceitar a Cura Espiritual");
        this.ações.add("Conecte-se a sua centelha divina e atraia a alegria (OM)");
        this.ações.add("Para retirar o carma e a auto-obsessão e para terminar projetos inacabados");
        this.ações.add("Liberte-se daquilo que te aprisiona");
        this.ações.add("Identifique seus pontos fracos");
        this.ações.add("\"Teus pecados foram perdoados, vá e não erres mais\"(Jesus)");
        this.ações.add("Sexo saudável e positivo Aprenda a ser humilde");
        this.ações.add("Ativar a coragem e eliminar o medo");
        this.ações.add("Conectando- se às Bênçãos do Eu Superior");
        this.ações.add("Prosperidade: Compartilhar para Receber e Receber para Compartilhar");
        this.ações.add("Volte a ter Sabor pela vida");
        this.ações.add("Fale as palavras certas, nas ocasiões certas");
        this.ações.add("Atraia a Compaixão e a Misericórdia e Melhore a Auto-Estima");
        this.ações.add("Acessando Segredos");
        this.ações.add("Redenção das almas sob domínio das trevas e Controlando o próprio destino");
        this.ações.add("Amenizando julgamentos carmicos");
        this.ações.add("Atraindo Prosperidade e Sustento Físico e Financeiro");
        this.ações.add("Certeza e Autoconfiança");
        this.ações.add("Acelerar a evolução espiritual");
        this.ações.add("Unindo os opostos");
        this.ações.add("Retificar o Passado desde a Semente da Criação e Atrair a felicidade");
        this.ações.add("Pense Grande: você pode contentar-se com muito");
        this.ações.add("Retirar as Sementes de Culpa");
        this.ações.add("Ativar o Fogo da Paixão Espiritual");
        this.ações.add("Atraindo Proteção, Cura e Amizades Verdadeiras");
        this.ações.add("Atrair o Fluxo da Vida");
        this.ações.add("Transformar o seu Destino");
        this.ações.add("Retirando a raiva e o pensamento de dependência");
        this.ações.add("Acessando os arquivos espirituais e os propósitos de nossa alma");
        this.ações.add("Transformando o Ego negativo num “agente” positivo e construtivo. Derrotar a escuridão interior");
        this.ações.add("Pare de remoer as trevas e seja uma usina da Luz de Deus");
        this.ações.add("Liberte-se da depressão e das limitações físicas e espirituais");
        this.ações.add("Devolva à água o seu poder divino");
        this.ações.add("Melhorando Relacionamentos e laços afetivos");
        this.ações.add("Ativando a Valorização, o Reconhecimento e a Gratidão Interior e Exterior");
        this.ações.add("Afastar a negatividade das críticas destrutivas e Ativar o magnetismo físico e espiritual");
        this.ações.add("Desperte a chama divina em seu coração e no coração de outras pessoas Aceite agir de acordo com a sua alma");
        this.ações.add("Afaste o sentimento de vingança e de vitimismo. Assuma a responsabilidade por seus atos");
        this.ações.add("Gerencie o seu tempo e aprenda a valorizar o que possui A espiritualidade é aqui e agora, em todos os momentos de sua vida");
        this.ações.add("Eleve as almas de pessoas que partiram para a Luz. Acesse conselhos de seres que te amam e partiram");
        this.ações.add("Ativar a clarividência e enxergar a espiritualidade Encontre seu caminho para Deus");
        this.ações.add("Elimine os bloqueios psiquicos do sucesso");
        this.ações.add("Ative o dom da profecia e a sabedoria divina");
        this.ações.add("Ative a Capacidade da Negociação. Purifique seu espírito e ambientes limpando resíduos energéticos");


        this.ownDecreto = "Eu, (nome do terapeuta) peço permissão ao Eu Superior de (nome do consulente) para aceder ao seu campo morfogenético, chakras e corpos sutis que se encontram afetados pela anomalia de (anomalia deus) para que se harmonizaem, equilibrem e criem impacto na estrutura do DNA, reestruturando e renovando o funcionamento do corpo físico na medida certa e na quantidade exata, dentro do que é divino. Eu ativo agora (nome de deus) para que (ação), promovendo a harmonização de todos os chakras e todos os campos sutis. Pulsa no campo, pulsa no campo, pulsa no campo.";
        
    }
}
