package com.portais.Ferramentas;

import com.portais.Ferramenta;
import com.portais.SubFerramenta;

public class PontosAcupuntura extends SubFerramenta{
    public PontosAcupuntura(Ferramenta mainFerramenta){
        super(mainFerramenta, "Pontos Acupuntura");
        this.multi = true;

        this.resultados.add("VC1 (Chengqi)");
        this.resultados.add("VC2 (Qugu)");
        this.resultados.add("VC3 (Zhongji)");
        this.resultados.add("VC4 (Guanyuan)");
        this.resultados.add("VC5 (Shimen)");
        this.resultados.add("VC6 (Qihai)");
        this.resultados.add("VC7 (Yinjiao)");
        this.resultados.add("VC8 (Shenque)");
        this.resultados.add("VC9 (Shuifen)");
        this.resultados.add("VC10 (Xiawan)");
        this.resultados.add("VC11 (Jianli)");
        this.resultados.add("VC12 (Zhongwan)");
        this.resultados.add("VC13 (Shangwan)");
        this.resultados.add("VC14 (Juque)");
        this.resultados.add("VC15 (Jiuwei)");
        this.resultados.add("VC16 (Zhongting)");
        this.resultados.add("VC17 (Shanzhong)");
        this.resultados.add("VC18 (Quze)");
        this.resultados.add("VC19 (Zigong)");
        this.resultados.add("VC20 (Huaroumen)");
        this.resultados.add("VC21 (Xuanji)");
        this.resultados.add("VC22 (Tiantu)");
        this.resultados.add("VC23 (Lianquan)");
        this.resultados.add("VC24 (Chengjiang)");
        this.resultados.add("VC25 (Tianshu)");
        this.resultados.add("VC26 (Wailing)");
        this.resultados.add("VC27 (Shufu)");
        this.resultados.add("VC28 (Shuidao)");
        this.resultados.add("E1 (Jingming)");
        this.resultados.add("E2 (Yuyao)");
        this.resultados.add("E3 (Yuyue)");
        this.resultados.add("E4 (Guanchong)");
        this.resultados.add("E5 (Tongziliao)");
        this.resultados.add("E6 (Pizhixue)");
        this.resultados.add("E7 (Qichong)");
        this.resultados.add("E8 (Shangming)");
        this.resultados.add("E9 (Zanzhu)");
        this.resultados.add("E10 (Tianzhu)");
        this.resultados.add("E11 (Touwei)");
        this.resultados.add("E12 (Fengmen)");
        this.resultados.add("E13 (Baihui)");
        this.resultados.add("E14 (Jianjing)");
        this.resultados.add("E15 (Tianliao)");
        this.resultados.add("E16 (Fengchi)");
        this.resultados.add("E17 (Wangu)");
        this.resultados.add("E18 (Quchi)");
        this.resultados.add("E19 (Luxi)");
        this.resultados.add("E20 (Zhouliao)");
        this.resultados.add("E21 (Li Neiguan)");
        this.resultados.add("E22 (Shangliao)");
        this.resultados.add("E23 (Shenshu)");
        this.resultados.add("E24 (Yaoyangguan)");
        this.resultados.add("E25 (Tianshu)");
        this.resultados.add("E26 (Wailing)");
        this.resultados.add("E27 (Daju)");
        this.resultados.add("B1 (Jingming)");
        this.resultados.add("B2 (Zanzhu)");
        this.resultados.add("B3 (Meichong)");
        this.resultados.add("B4 (Xuanlu)");
        this.resultados.add("B5 (Tongziliao)");
        this.resultados.add("B6 (Chengqi)");
        this.resultados.add("B7 (Guanchong)");
        this.resultados.add("B8 (Erbai)");
        this.resultados.add("B9 (Taiyang)");
        this.resultados.add("B10 (Tianzhu)");
        this.resultados.add("B11 (Fengmen)");
        this.resultados.add("B12 (Fengmen)");
        this.resultados.add("B13 (Feishu)");
        this.resultados.add("B14 (Jueyinshu)");
        this.resultados.add("B15 (Xinshu)");
        this.resultados.add("B16 (Dushu)");
        this.resultados.add("B17 (Geshu)");
        this.resultados.add("B18 (Ganshu)");
        this.resultados.add("B19 (Danshu)");
        this.resultados.add("B20 (Pishu)");
        this.resultados.add("B21 (Weishu)");
        this.resultados.add("B22 (Sanjiaoshu)");
        this.resultados.add("B23 (Shenshu)");
        this.resultados.add("B24 (Qihaishu)");
        this.resultados.add("B25 (Dachangshu)");
        this.resultados.add("B26 (Guanyuanshu)");
        this.resultados.add("B27 (Xiaochangshu");
        this.resultados.add("B28 (Pangguangshu");
        this.resultados.add("B29 (Zhonglushu)");
        this.resultados.add("B30 (Baihuanshu)");
        this.resultados.add("B31 (Shangliao)");
        this.resultados.add("B32 (Ciliao)");
        this.resultados.add("B33 (Zhongliao)");
        this.resultados.add("B34 (Xialiao)");
        this.resultados.add("B35 (Huiyang)");
        this.resultados.add("B36 (Chengfu)");
        this.resultados.add("B37 (Yinmen)");
        this.resultados.add("B38 (Fufen)");
        this.resultados.add("B39 (Weiyang)");
        this.resultados.add("B40 (Weizhong)");
        this.resultados.add("B41 (Fuqi)");
        this.resultados.add("B42 (Pohu)");
        this.resultados.add("B43 (Gaohuangshu)");
        this.resultados.add("B44 (Shentang)");
        this.resultados.add("B45 (Jinmen)");
        this.resultados.add("B46 (Guanmen)");
        this.resultados.add("B47 (Hunmen)");
        this.resultados.add("B48 (Yanggang)");
        this.resultados.add("B49 (Yishe)");
        this.resultados.add("B50 (Weicang)");
        this.resultados.add("B51 (Huangmen)");
        this.resultados.add("B52 (Zhiyang)");
        this.resultados.add("B53 (Baichongwo)");
        this.resultados.add("B54 (Zhibian)");
        this.resultados.add("B55 (Wushu)");
        this.resultados.add("B56 (Chengjin)");
        this.resultados.add("B57 (Chengshan)");
        this.resultados.add("B58 (Feiyang)");
        this.resultados.add("B59 (Fuyang)");
        this.resultados.add("B60 (Kunlun)");
        this.resultados.add("B61 (Pucan)");
        this.resultados.add("B62 (Shenmai)");
        this.resultados.add("B63 (Jinmen)");
        this.resultados.add("B64 (Jinggu)");
        this.resultados.add("B65 (Shugu)");
        this.resultados.add("B66 (Zutonggu)");
        this.resultados.add("B67 (Zhiyin)");
        this.resultados.add("B68 (Chengjin)");
        this.resultados.add("B69 (Fengshi)");
        this.resultados.add("B70 (Fengshi)");
        this.resultados.add("B71 (Lingdao)");
        this.resultados.add("B72 (Zhibian)");
        this.resultados.add("B73 (Shenmai)");
        this.resultados.add("B74 (Jinlingquan)");
        this.resultados.add("B75 (Yinshi)");
        this.resultados.add("B76 (Daimai)");
        this.resultados.add("B77 (Ganshu)");
        this.resultados.add("B78 (Zhiyin)");
        this.resultados.add("B79 (Yinshi)");
        this.resultados.add("B80 (Fengshi)");
        this.resultados.add("B81 (Weizhong)");
        this.resultados.add("B82 (Chengjin)");
        this.resultados.add("B83 (Qiuxu)");
        this.resultados.add("B84 (Fengchi)");
        this.resultados.add("B85 (Yanglingquan)");
        this.resultados.add("B86 (Huangmen)");
        this.resultados.add("B87 (Huizong)");
        this.resultados.add("B88 (Chengshan)");
        this.resultados.add("B89 (Wailing)");
        this.resultados.add("B90 (Yingu)");
        this.resultados.add("B91 (Shuifen)");
        this.resultados.add("B92 (Shuifen)");
        this.resultados.add("B93 (Yinmen)");
        this.resultados.add("B94 (Zutonggu)");
        this.resultados.add("B95 (Chengfu)");
        this.resultados.add("B96 (Weicang)");
        this.resultados.add("B97 (Zhiyang)");
        this.resultados.add("B98 (Huangmen)");
        this.resultados.add("B99 (Shugu)");
        this.resultados.add("B100 (Shugu)");
        this.resultados.add("B101 (Shugu)");
        this.resultados.add("B102 (Shugu)");
        this.resultados.add("B103 (Shugu)");
        this.resultados.add("B104 (Shugu)");
        this.resultados.add("B105 (Shugu)");
        this.resultados.add("B106 (Shugu)");
        this.resultados.add("B107 (Shugu)");
        this.resultados.add("B108 (Shugu)");
        this.resultados.add("B109 (Shugu)");
        this.resultados.add("B110 (Shugu)");
        this.resultados.add("B111 (Shugu)");
        this.resultados.add("B112 (Shugu)");
        this.resultados.add("B113 (Shugu)");
        this.resultados.add("B114 (Shugu)");
        this.resultados.add("B115 (Shugu)");
        this.resultados.add("B116 (Shugu)");
        this.resultados.add("B117 (Shugu)");
        this.resultados.add("B118 (Shugu)");
        this.resultados.add("B119 (Shugu)");
        this.resultados.add("B120 (Shugu)");
        this.resultados.add("B121 (Shugu)");
        this.resultados.add("B122 (Shugu)");
        this.resultados.add("B123 (Shugu)");
        this.resultados.add("B124 (Shugu)");
        this.resultados.add("B125 (Shugu)");
        this.resultados.add("B126 (Shugu)");
        this.resultados.add("B127 (Shugu)");
        this.resultados.add("B128 (Shugu)");
        this.resultados.add("B129 (Shugu)");
        this.resultados.add("B130 (Shugu)");
        this.resultados.add("B131 (Shugu)");
        this.resultados.add("B132 (Shugu)");
        this.resultados.add("B133 (Shugu)");
        this.resultados.add("B134 (Shugu)");
        this.resultados.add("B135 (Shugu)");
        this.resultados.add("B136 (Shugu)");
        this.resultados.add("B137 (Shugu)");
        this.resultados.add("B138 (Shugu)");
        this.resultados.add("B139 (Shugu)");
        this.resultados.add("B140 (Shugu)");
        this.resultados.add("B141 (Shugu)");
        this.resultados.add("B142 (Shugu)");
        this.resultados.add("B143 (Shugu)");
        this.resultados.add("B144 (Shugu)");
        this.resultados.add("B145 (Shugu)");
        this.resultados.add("B146 (Shugu)");
        this.resultados.add("B147 (Shugu)");
        this.resultados.add("B148 (Shugu)");
        this.resultados.add("B149 (Shugu)");
        this.resultados.add("B150 (Shugu)");
        this.resultados.add("B151 (Shugu)");
        this.resultados.add("B152 (Shugu)");
        this.resultados.add("B153 (Shugu)");
        this.resultados.add("B154 (Shugu)");
        this.resultados.add("B155 (Shugu)");
        this.resultados.add("B156 (Shugu)");
        this.resultados.add("B157 (Shugu)");
        this.resultados.add("B158 (Shugu)");
        this.resultados.add("B159 (Shugu)");
        this.resultados.add("B160 (Shugu)");
        this.resultados.add("B161 (Shugu)");
        this.resultados.add("B162 (Shugu)");
        this.resultados.add("B163 (Shugu)");
        this.resultados.add("B164 (Shugu)");
        this.resultados.add("B165 (Shugu)");
        this.resultados.add("B166 (Shugu)");
        this.resultados.add("B167 (Shugu)");
        this.resultados.add("B168 (Shugu)");
        this.resultados.add("B169 (Shugu)");
        this.resultados.add("B170 (Shugu)");
        this.resultados.add("B171 (Shugu)");
        this.resultados.add("B172 (Shugu)");
        this.resultados.add("B173 (Shugu)");
        this.resultados.add("B174 (Shugu)");
        this.resultados.add("B175 (Shugu)");
        this.resultados.add("B176 (Shugu)");
        this.resultados.add("B177 (Shugu)");
        this.resultados.add("B178 (Shugu)");
        this.resultados.add("B179 (Shugu)");
        this.resultados.add("B180 (Shugu)");
        this.resultados.add("B181 (Shugu)");
        this.resultados.add("B182 (Shugu)");
        this.resultados.add("B183 (Shugu)");
        this.resultados.add("B184 (Shugu)");
        this.resultados.add("B185 (Shugu)");
        this.resultados.add("B186 (Shugu)");
        this.resultados.add("B187 (Shugu)");
        this.resultados.add("B188 (Shugu)");
        this.resultados.add("B189 (Shugu)");
        this.resultados.add("B190 (Shugu)");
        this.resultados.add("B191 (Shugu)");
        this.resultados.add("B192 (Shugu)");
        this.resultados.add("B193 (Shugu)");
        this.resultados.add("B194 (Shugu)");
        this.resultados.add("B195 (Shugu)");
        this.resultados.add("B196 (Shugu)");
        this.resultados.add("B197 (Shugu)");
        this.resultados.add("B198 (Shugu)");
        this.resultados.add("B199 (Shugu)");
        this.resultados.add("B200 (Shugu)");
        this.resultados.add("B201 (Shugu)");
        this.resultados.add("B202 (Shugu)");
        this.resultados.add("B203 (Shugu)");
        this.resultados.add("B204 (Shugu)");
        this.resultados.add("B205 (Shugu)");
        this.resultados.add("B206 (Shugu)");
        this.resultados.add("B207 (Shugu)");
        this.resultados.add("B208 (Shugu)");
        this.resultados.add("B209 (Shugu)");
        this.resultados.add("B210 (Shugu)");
        this.resultados.add("B211 (Shugu)");
        this.resultados.add("B212 (Shugu)");
        this.resultados.add("B213 (Shugu)");
        this.resultados.add("B214 (Shugu)");
        this.resultados.add("B215 (Shugu)");
        this.resultados.add("B216 (Shugu)");
        this.resultados.add("B217 (Shugu)");
        this.resultados.add("B218 (Shugu)");
        this.resultados.add("B219 (Shugu)");
        this.resultados.add("B220 (Shugu)");
        this.resultados.add("B221 (Shugu)");
        this.resultados.add("B222 (Shugu)");
        this.resultados.add("B223 (Shugu)");
        this.resultados.add("B224 (Shugu)");
        this.resultados.add("B225 (Shugu)");
        this.resultados.add("B226 (Shugu)");
        this.resultados.add("B227 (Shugu)");
        this.resultados.add("B228 (Shugu)");
        this.resultados.add("B229 (Shugu)");
        this.resultados.add("B230 (Shugu)");
        this.resultados.add("B231 (Shugu)");
        this.resultados.add("B232 (Shugu)");
        this.resultados.add("B233 (Shugu)");
        this.resultados.add("B234 (Shugu)");
        this.resultados.add("B235 (Shugu)");
        this.resultados.add("B236 (Shugu)");
        this.resultados.add("B237 (Shugu)");
        this.resultados.add("B238 (Shugu)");
        this.resultados.add("B239 (Shugu)");
        this.resultados.add("B240 (Shugu)");
        this.resultados.add("B241 (Shugu)");
        this.resultados.add("B242 (Shugu)");
        this.resultados.add("B243 (Shugu)");
        this.resultados.add("B244 (Shugu)");
        this.resultados.add("B245 (Shugu)");
        this.resultados.add("B246 (Shugu)");
        this.resultados.add("B247 (Shugu)");
        this.resultados.add("B248 (Shugu)");
        this.resultados.add("B249 (Shugu)");
        this.resultados.add("B250 (Shugu)");
        this.resultados.add("B251 (Shugu)");
        this.resultados.add("B252 (Shugu)");
        this.resultados.add("B253 (Shugu)");
        this.resultados.add("B254 (Shugu)");
        this.resultados.add("B255 (Shugu)");
        this.resultados.add("B256 (Shugu)");
        this.resultados.add("B257 (Shugu)");
        this.resultados.add("B258 (Shugu)");
        this.resultados.add("B259 (Shugu)");
        this.resultados.add("B260 (Shugu)");
        this.resultados.add("B261 (Shugu)");
        this.resultados.add("B262 (Shugu)");
        this.resultados.add("B263 (Shugu)");
        this.resultados.add("B264 (Shugu)");
        this.resultados.add("B265 (Shugu)");
        this.resultados.add("B266 (Shugu)");
        this.resultados.add("B267 (Shugu)");
        this.resultados.add("B268 (Shugu)");
        this.resultados.add("B269 (Shugu)");
        this.resultados.add("B270 (Shugu)");
        this.resultados.add("B271 (Shugu)");
        this.resultados.add("B272 (Shugu)");
        this.resultados.add("B273 (Shugu)");
        this.resultados.add("B274 (Shugu)");
        this.resultados.add("B275 (Shugu)");
        this.resultados.add("B276 (Shugu)");
        this.resultados.add("B277 (Shugu)");
        this.resultados.add("B278 (Shugu)");
        this.resultados.add("B279 (Shugu)");
        this.resultados.add("B280 (Shugu)");
        this.resultados.add("B281 (Shugu)");
        this.resultados.add("B282 (Shugu)");
        this.resultados.add("B283 (Shugu)");
        this.resultados.add("B284 (Shugu)");
        this.resultados.add("B285 (Shugu)");
        this.resultados.add("B286 (Shugu)");
        this.resultados.add("B287 (Shugu)");
        this.resultados.add("B288 (Shugu)");
        this.resultados.add("B289 (Shugu)");
        this.resultados.add("B290 (Shugu)");
        this.resultados.add("B291 (Shugu)");
        this.resultados.add("B292 (Shugu)");
        this.resultados.add("B293 (Shugu)");
        this.resultados.add("B294 (Shugu)");
        this.resultados.add("B295 (Shugu)");
        this.resultados.add("B296 (Shugu)");
        this.resultados.add("B297 (Shugu)");
        this.resultados.add("B298 (Shugu)");
        this.resultados.add("B299 (Shugu)");
        this.resultados.add("B300 (Shugu)");


        this.ações.add("Abdominal distendido, dor e constipação");
        this.ações.add("Dor abdominal, distensão, menstruação irregular");
        this.ações.add("Dor abdominal, incontinência urinária");
        this.ações.add("Dor abdominal, problemas menstruais, infertilidade");
        this.ações.add("Dor abdominal, distensão, incontinência urinária");
        this.ações.add("Fraqueza geral, dor lombar, impotência");
        this.ações.add("Regulação hormonal, distúrbios menstruais");
        this.ações.add("Dor abdominal, diarreia, constipação");
        this.ações.add("Dor abdominal, inchaço, retenção de líquidos");
        this.ações.add("Dor abdominal, indigestão, azia");
        this.ações.add("Dor abdominal, constipação, diarreia");
        this.ações.add("Indigestão, distensão abdominal, náuseas");
        this.ações.add("Indigestão, refluxo ácido, distensão abdominal");
        this.ações.add("Ansiedade, depressão, distúrbios emocionais");
        this.ações.add("Dor no peito, falta de ar, tosse");
        this.ações.add("Tosse, dor no peito, dificuldade em respirar");
        this.ações.add("Dor no peito, tosse, asma");
        this.ações.add("Dor no peito, tosse, falta de ar");
        this.ações.add("Problemas menstruais, infertilidade, dor abdominal");
        this.ações.add("Problemas digestivos, distensão abdominal");
        this.ações.add("Dor epigástrica, distensão abdominal");
        this.ações.add("Dor de garganta, dificuldade em engolir");
        this.ações.add("Dor de garganta, rouquidão, problemas vocais");
        this.ações.add("Dificuldade em abrir a boca, dor no queixo");
        this.ações.add("Constipação, diarreia, distúrbios intestinais");
        this.ações.add("Dor abdominal, distúrbios intestinais");
        this.ações.add("Dor abdominal, inchaço, distúrbios intestinais");
        this.ações.add("Dor abdominal, distúrbios intestinais, inchaço");
        this.ações.add("Dor ocular, vermelhidão, coceira");
        this.ações.add("Dor ocular, visão turva, lacrimejamento");
        this.ações.add("Dor ocular, olhos secos, visão turva");
        this.ações.add("Dor ocular, lacrimejamento, vermelhidão");
        this.ações.add("Dor ocular, coceira, conjuntivite");
        this.ações.add("Dor ocular, visão turva, coceira");
        this.ações.add("Dor ocular, vermelhidão, lacrimejamento");
        this.ações.add("Dor ocular, coceira, sensação de areia");
        this.ações.add("Dor de cabeça, sinusite, enxaqueca");
        this.ações.add("Dor de cabeça, enxaqueca, tontura");
        this.ações.add("Dor de cabeça, enxaqueca, problemas de visão");
        this.ações.add("Dor de cabeça, enxaqueca, rigidez no pescoço");
        this.ações.add("Dor de cabeça, tontura, vertigem");
        this.ações.add("Dor no ombro, tensão muscular");
        this.ações.add("Dor no ombro, tensão muscular, enxaqueca");
        this.ações.add("Dor de cabeça, enxaqueca, tontura");
        this.ações.add("Dor de cabeça, dor no pescoço, rigidez");
        this.ações.add("Dor no braço, dor no cotovelo, problemas digestivos");
        this.ações.add("Dor no braço, dor no cotovelo, rigidez");
        this.ações.add("Dor no braço, dor no cotovelo, tensão muscular");
        this.ações.add("Náusea, vômito, enjoo");
        this.ações.add("Dor lombar, dor na região sacral");
        this.ações.add("Dor lombar, fraqueza nas pernas");
        this.ações.add("Dor lombar, dor na região sacral");
        this.ações.add("Distúrbios intestinais, constipação, diarreia");
        this.ações.add("Distúrbios intestinais, constipação, diarreia");
        this.ações.add("Distúrbios intestinais, constipação, diarreia");
        this.ações.add("Dor de cabeça, vermelhidão ocular");
        this.ações.add("Dor de cabeça, sinusite, dor ocular");
        this.ações.add("Dor ocular, lacrimejamento, coceira");
        this.ações.add("Dor ocular, coceira, visão turva");
        this.ações.add("Dor ocular, visão turva, coceira");
        this.ações.add("Dor ocular, dor de garganta, rouquidão");
        this.ações.add("Dor ocular, lacrimejamento, vermelhidão");
        this.ações.add("Dor ocular, lacrimejamento, vermelhidão");
        this.ações.add("Dor de cabeça, enxaqueca, dor ocular");
        this.ações.add("Dor de cabeça, rigidez no pescoço");
        this.ações.add("Dor de cabeça, tontura, rigidez no pescoço");
        this.ações.add("Dor de cabeça, enxaqueca, tontura");
        this.ações.add("Tosse, falta de ar, problemas respiratórios");
        this.ações.add("Tosse, asma, falta de ar");
        this.ações.add("Dor no peito, palpitações, falta de ar");
        this.ações.add("Tosse, asma, falta de ar");
        this.ações.add("Tosse, falta de ar, dor no peito");
        this.ações.add("Dor no peito, tosse, falta de ar");
        this.ações.add("Dor no peito, tosse, falta de ar");
        this.ações.add("Problemas digestivos, falta de apetite");
        this.ações.add("Problemas digestivos, indigestão, distensão abdominal");
        this.ações.add("Dor lombar, fraqueza nas pernas, impotência");
        this.ações.add("Dor lombar, fraqueza nas pernas, impotência");
        this.ações.add("Dor lombar, problemas renais, impotência");
        this.ações.add("Constipação, diarreia, distúrbios intestinai");
        this.ações.add("Dor lombar, problemas renais, impotência");
        this.ações.add("Constipação, diarreia, distúrbios intestinais");
        this.ações.add("Problemas urinários, dor lombar");
        this.ações.add("Dor lombar, dor nas nádegas");
        this.ações.add("Dor lombar, dor nas nádegas");
        this.ações.add("Dor lombar, fraqueza nas pernas, impotência");
        this.ações.add("Dor lombar, fraqueza nas pernas, impotência");
        this.ações.add("Dor lombar, fraqueza nas pernas, impotência");
        this.ações.add("Dor lombar, fraqueza nas pernas, impotência");
        this.ações.add("Dor lombar, problemas urinários, impotência");
        this.ações.add("Dor lombar, problemas urinários, impotência");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, impotência");
        this.ações.add("Dor lombar, dor nas pernas, impotência");
        this.ações.add("Dor lombar, dor nas pernas, impotência");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor lombar, dor nas pernas, problemas renais");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor no calcanhar, dor no tornozelo");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");
        this.ações.add("Dor nas costas, dor lombar");

        this.repeatString = "(designação) para (ação), ";
        this.ownDecreto = "Na divina presença do Eu Sou de (nome do terapeuta) abro a frequência do método de Cura Quântica Multidimensional e a Matriz da Bioenergética Sutil pedindo ao Eu Superior de (nome do consulente) permissão para atuar nos seus pontos energéticos de acupuntura. Ativo agora a frequência dos pontos de acupuntura (next) desbloqueando as condensações energéticas reajustando e equilibrando o seu fluxo normal para limpar os registros de doença ou prevenir o seu aparecimento. Que pulse(m) na harmonia e alinhamento de consciência de (nome do consulente) na quantidade certa e na medida exata. Pulsa no campo, pulsa no campo, pulsa no campo.";
    }
}
